apiVersion: v1
kind: Pod
metadata:
  name: "pod"
spec:
  containers:
  - name: Zenko-MD
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    image: "{{ images.mdproxy }}"
  - name: agressor
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    image: "{{ images.agressor }}"
    command: ["/bin/sh", "-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
